### ISSUE TITLE
Recording Money SP conversion off 

### ISSUE THREAD

**Issue by tuhs1985** [keyneston/vttmud#26]
When I record it, it looks like this
![image](https://github.com/keyneston/vttmud/assets/77306309/81189f15-1d51-403b-a8cd-b6ad2bd759b4)
But when i save it, it looks like this
![image](https://github.com/keyneston/vttmud/assets/77306309/93a8a020-b435-4df0-9bed-05a180adc510)

SP conversion seems to be off.

**Comment by tuhs1985** [comment]
This may be a display issue, it seems to be totaling them correctly.

**Comment by keyneston** [comment]
Interesting, this only seems to happen if the copper is more than 5 which means this is some kind of rounding error when calculating the display value. Should hopefully have it resolved soon.

**Comment by keyneston** [comment]
Perfect. Looks like the change I made last night worked. Mind taking another look?
